{
  "hash": "a77ac8d94116c0d10432b8d92a1c0676",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"R lecture 4: Meta-analysis in R II\"\nsubtitle: \"SKI3011 · binary and continuous outcomes, published odds ratios, the meta package\"\n# This page is also the lecture script: scripts/render-r-lectures.sh turns it into an .R file\n# in which all text below becomes comments, so students can run it line by line in RStudio.\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n**How to use this lecture.** Download the R script, open it in RStudio and run it line by line (Cmd+Enter on a Mac, Ctrl+Enter on Windows). All explanations on this page are in the script as comments. Check that you get the same output as shown here. Quiz 3 asks you to read and interpret exactly this kind of code and output.\n\n[Download the R script](../materials/ski3011/week-4/r-lecture-4.R){.btn .btn-primary}\n\n## Packages\n\nToday we use two packages. `metafor` you know from last week. `meta` does the same with slightly different functions (`metabin()`, `metacont()`, `metagen()`) and makes nice forest plots. Many published reviews use one of the two.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"meta\")   # run once\nlibrary(metafor)\nlibrary(meta)\nlibrary(metadat)\n```\n:::\n\n\n## Binary outcomes: the data\n\nNine trials on diuretics in pregnancy and the risk of pre-eclampsia (dat.collins1985b). For each trial we need the number of events and the group size in the treatment and the control group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- dat.collins1985b[, c(\"author\", \"year\", \"pre.xti\", \"pre.nti\", \"pre.xci\", \"pre.nci\")]\ndat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   author year pre.xti pre.nti pre.xci pre.nci\n1       Weseley & Douglas 1962      14     131      14     136\n2          Flowers et al. 1962      21     385      17     134\n3                 Menzies 1964      14      57      24      48\n4           Fallis et al. 1964       6      38      18      40\n5         Cuadros & Tatum 1964      12    1011      35     760\n6        Landesman et al. 1965     138    1370     175    1336\n7            Kraus et al. 1966      15     506      20     524\n8    Tervila & Vartiainen 1971       6     108       2     103\n9 Campbell & MacGillivray 1975      65     153      40     102\n```\n\n\n:::\n:::\n\n\n## Binary outcomes with metafor\n\nInstead of the four cells (`ai`, `bi`, `ci`, `di`) you can give the events and group sizes (`ai`, `n1i`, `ci`, `n2i`). The odds ratio is pooled on the log scale.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- escalc(measure = \"OR\",\n              ai = pre.xti, n1i = pre.nti,   # events and group size, treatment\n              ci = pre.xci, n2i = pre.nci,   # events and group size, control\n              data = dat, slab = paste(author, year))\nres <- rma(yi, vi, data = dat)\npredict(res, transf = exp, digits = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n pred ci.lb ci.ub pi.lb pi.ub \n 0.60  0.38  0.92  0.19  1.90 \n```\n\n\n:::\n:::\n\n\nDiuretics lower the odds of pre-eclampsia (OR 0.60, 95% CI 0.38 to 0.92), but the prediction interval (0.19 to 1.90) shows that the effect in a new trial could be anything from strong protection to harm: the trials are very heterogeneous.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nforest(res, atransf = exp, header = TRUE)\n```\n\n::: {.cell-output-display}\n![](r-lecture-4_files/figure-html/unnamed-chunk-4-1.png){width=864}\n:::\n:::\n\n\n## Mantel-Haenszel\n\nThe Mantel-Haenszel method is a fixed-effect method that works directly on the counts and handles small numbers of events well.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrma.mh(measure = \"OR\", ai = pre.xti, n1i = pre.nti, ci = pre.xci, n2i = pre.nci,\n       data = dat, digits = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nEqual-Effects Model (k = 9)\n\nI^2 (total heterogeneity / total variability):  70.66%\nH^2 (total variability / sampling variability): 3.41\n\nTest for Heterogeneity: \nQ(df = 8) = 27.27, p-val < .01\n\nModel Results (log scale):\n\nestimate    se   zval  pval  ci.lb  ci.ub \n   -0.40  0.09  -4.60  <.01  -0.58  -0.23 \n\nModel Results (OR scale):\n\nestimate  ci.lb  ci.ub \n    0.67   0.56   0.79 \n\nCochran-Mantel-Haenszel Test:    CMH = 21.23, df = 1, p-val < 0.01\nTarone's Test for Heterogeneity: X^2 = 28.79, df = 8, p-val < 0.01\n```\n\n\n:::\n:::\n\n\n## Binary outcomes with meta\n\n`metabin()` from the meta package gives the fixed-effect (called \"common effect\") and the random-effects result in one go. Studies with zero events in one group get a continuity correction of 0.5 (`incr`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_bin <- metabin(event.e = pre.xti, n.e = pre.nti,   # experimental group\n                 event.c = pre.xci, n.c = pre.nci,   # control group\n                 sm = \"OR\", data = dat,\n                 studlab = paste(author, year))\nsummary(m_bin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                 OR            95%-CI %W(common) %W(random)\nWeseley & Douglas 1962       1.0427 [0.4766;  2.2815]        3.9       10.9\nFlowers et al. 1962          0.3971 [0.2027;  0.7779]        7.5       11.9\nMenzies 1964                 0.3256 [0.1424;  0.7444]        6.2       10.4\nFallis et al. 1964           0.2292 [0.0785;  0.6692]        4.6        8.3\nCuadros & Tatum 1964         0.2488 [0.1283;  0.4827]       12.4       12.0\nLandesman et al. 1965        0.7431 [0.5863;  0.9420]       50.1       15.9\nKraus et al. 1966            0.7699 [0.3897;  1.5210]        6.0       11.9\nTervila & Vartiainen 1971    2.9706 [0.5857; 15.0675]        0.6        5.1\nCampbell & MacGillivray 1975 1.1449 [0.6871;  1.9078]        8.7       13.6\n\nNumber of studies: k = 9\nNumber of observations: o = 6942 (o.e = 3759, o.c = 3183)\nNumber of events: e = 636\n\n                         OR           95%-CI     z  p-value\nCommon effect model  0.6677 [0.5620; 0.7932] -4.60 < 0.0001\nRandom effects model 0.5956 [0.3843; 0.9233] -2.32   0.0205\n\nQuantifying heterogeneity (with 95%-CIs):\n tau^2 = 0.3008 [0.0723; 2.2027]; tau = 0.5484 [0.2689; 1.4842]\n I^2 = 70.7% [41.8%; 85.2%]; H = 1.85 [1.31; 2.60]\n\nTest of heterogeneity:\n     Q d.f. p-value\n 27.26    8  0.0006\n\nDetails of meta-analysis methods:\n- Mantel-Haenszel method (common effect model)\n- Inverse variance method (random effects model)\n- Restricted maximum-likelihood estimator for tau^2\n- Q-Profile method for confidence interval of tau^2 and tau\n- Calculation of I^2 based on Q\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nforest(m_bin)\n```\n\n::: {.cell-output-display}\n![](r-lecture-4_files/figure-html/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\n## Published odds ratios with a confidence interval\n\nOften a paper only reports an odds ratio with its 95% CI. Then you calculate the log odds ratio and its standard error yourself: SE = [ln(upper) − ln(lower)] / 3.92. Example: 37 studies on passive smoking and lung cancer in women (dat.hackshaw1998).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsmoke <- dat.hackshaw1998[, c(\"author\", \"year\", \"or\", \"or.lb\", \"or.ub\")]\nsmoke$log_or <- log(smoke$or)\nsmoke$se_log_or <- (log(smoke$or.ub) - log(smoke$or.lb)) / 3.92   # SE from the 95% CI\nhead(smoke, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     author year   or or.lb or.ub    log_or se_log_or \n1 Garfinkel 1981 1.18  0.90  1.54 0.1655144 0.1370263 \n2  Hirayama 1984 1.45  1.02  2.08 0.3715636 0.1817769 \n3    Butler 1988 2.02  0.48  8.56 0.7030975 0.7349667 \n```\n\n\n:::\n:::\n\n\n`metagen()` pools any pre-calculated effect size: `TE` is the effect (here the log OR) and `seTE` its standard error. With `sm = \"OR\"` the output is shown as odds ratios.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_gen <- metagen(TE = log_or, seTE = se_log_or, sm = \"OR\",\n                 data = smoke, studlab = paste(author, year))\nsummary(m_gen)$random    # random-effects result on the log scale\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$TE\n[1] 0.2188913\n\n$seTE\n[1] 0.04939564\n\n$lower\n[1] 0.1220777\n\n$upper\n[1] 0.315705\n\n$statistic\n[1] 4.43139\n\n$p\n[1] 9.36276e-06\n\n$level\n[1] 0.95\n\n$df\n[1] Inf\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(c(m_gen$TE.random, m_gen$lower.random, m_gen$upper.random))   # as odds ratio\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.244696 1.129842 1.371226\n```\n\n\n:::\n:::\n\n\nWomen exposed to environmental tobacco smoke have about 24% higher odds of lung cancer (OR 1.24, 95% CI 1.13 to 1.37).\n\n## Continuous outcomes: mean difference\n\nFive studies comparing pain scores (NRS, 0 to 10) after two types of spinal fusion surgery, TLIF and PLIF. All studies use the same scale, so we pool the mean difference (MD).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAuthor   <- c(\"Yang\", \"Han\", \"Liu\", \"Yan\", \"Sakeb\")\nYear     <- c(2015, 2016, 2016, 2008, 2013)\nN_TLIF   <- c(32, 36, 101, 91, 50)\nNRS_TLIF <- c(1.33, 2.44, 2.84, 2.84, 1.83)\nSD_TLIF  <- c(0.89, 1.42, 0.91, 0.91, 0.63)\nN_PLIF   <- c(34, 26, 125, 85, 52)\nNRS_PLIF <- c(1.26, 2.65, 2.84, 2.84, 2.00)\nSD_PLIF  <- c(0.76, 1.26, 0.89, 0.89, 0.67)\npain <- data.frame(Author, Year, N_TLIF, NRS_TLIF, SD_TLIF, N_PLIF, NRS_PLIF, SD_PLIF)\n\nm_cont <- metacont(n.e = N_TLIF, mean.e = NRS_TLIF, sd.e = SD_TLIF,   # TLIF group\n                   n.c = N_PLIF, mean.c = NRS_PLIF, sd.c = SD_PLIF,   # PLIF group\n                   sm = \"MD\", data = pain, studlab = paste(Author, Year))\nsummary(m_cont)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                MD            95%-CI %W(common) %W(random)\nYang 2015   0.0700 [-0.3304; 0.4704]       11.1       11.1\nHan 2016   -0.2100 [-0.8806; 0.4606]        4.0        4.0\nLiu 2016    0.0000 [-0.2363; 0.2363]       31.9       31.9\nYan 2008    0.0000 [-0.2660; 0.2660]       25.1       25.1\nSakeb 2013 -0.1700 [-0.4223; 0.0823]       27.9       27.9\n\nNumber of studies: k = 5\nNumber of observations: o = 632 (o.e = 310, o.c = 322)\n\n                          MD            95%-CI     z p-value\nCommon effect model  -0.0481 [-0.1814; 0.0853] -0.71  0.4801\nRandom effects model -0.0481 [-0.1814; 0.0853] -0.71  0.4801\n\nQuantifying heterogeneity (with 95%-CIs):\n tau^2 = 0 [0.0000; 0.0712]; tau = 0 [0.0000; 0.2669]\n I^2 = 0.0% [0.0%; 79.2%]; H = 1.00 [1.00; 2.19]\n\nTest of heterogeneity:\n    Q d.f. p-value\n 1.74    4  0.7835\n\nDetails of meta-analysis methods:\n- Inverse variance method\n- Restricted maximum-likelihood estimator for tau^2\n- Q-Profile method for confidence interval of tau^2 and tau\n- Calculation of I^2 based on Q\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nforest(m_cont, label.e = \"TLIF\", label.c = \"PLIF\", xlab = \"Pain (NRS)\")\n```\n\n::: {.cell-output-display}\n![](r-lecture-4_files/figure-html/unnamed-chunk-11-1.png){width=960}\n:::\n:::\n\n\nThe pain scores hardly differ (MD −0.05, 95% CI −0.18 to 0.09) and there is no heterogeneity (I² = 0%).\n\n## Continuous outcomes: standardised mean difference\n\nWhen studies measure the same outcome on different scales, use the standardised mean difference (SMD, Hedges' g): the difference in means divided by the pooled standard deviation. Example: length of hospital stay after stroke in specialist versus routine care (dat.normand1999).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstroke <- escalc(measure = \"SMD\",\n                 m1i = m1i, sd1i = sd1i, n1i = n1i,   # specialist care\n                 m2i = m2i, sd2i = sd2i, n2i = n2i,   # routine care\n                 data = dat.normand1999, slab = source)\nres_smd <- rma(yi, vi, data = stroke)\nprint(res_smd, digits = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nRandom-Effects Model (k = 9; tau^2 estimator: REML)\n\ntau^2 (estimated amount of total heterogeneity): 0.79 (SE = 0.43)\ntau (square root of estimated tau^2 value):      0.89\nI^2 (total heterogeneity / total variability):   95.49%\nH^2 (total variability / sampling variability):  22.20\n\nTest for Heterogeneity:\nQ(df = 8) = 123.73, p-val < .01\n\nModel Results:\n\nestimate    se   zval  pval  ci.lb  ci.ub    \n   -0.54  0.31  -1.74  0.08  -1.14   0.07  . \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe pooled SMD is −0.54 (95% CI −1.14 to 0.07): a moderate reduction in length of stay, but not statistically significant, and with very large heterogeneity (I² = 95%).\n\n## Saving a forest plot\n\nTo put a forest plot in your paper, save it as an image file. This is not run on the website.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npng(\"forest_plot.png\", width = 1000, height = 500)\nforest(m_cont, label.e = \"TLIF\", label.c = \"PLIF\", xlab = \"Pain (NRS)\")\ndev.off()\n```\n:::\n\n\n## Check yourself\n\nGo to the [concept list and practice quiz of week 4](week-4.qmd) and try the practice quiz without looking at this page.\n",
    "supporting": [
      "r-lecture-4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}